name: terraform plan
on:
  pull_request:

permissions:
  contents: read
  id-token: write
  pull-requests: write
jobs:
  archive:
    uses: ./.github/workflows/archive.yml
  plan:
    needs: archive
    # リポジトリ内ならいつでも走らせる
    # フォークでは context が異なり動かない。pull_request_target で代用する
    if: ${{ github.event.head.repo.id == github.event.base.repo.id }}
    uses: ./.github/workflows/terraform.yml
    with:
      command: plan
      tfcmt: true
    secrets:
      GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
      GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
      DISCORD_API_KEY: ${{ secrets.DISCORD_API_KEY }}
      DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
      DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
